import jwt from "jsonwebtoken";

function authMiddleware(req, res, next){
  const token = req.headers.authorization
  if (!token)
    return res.status(401).send("No token provided")

  try {
    const decoded = jwt.verify(token, process.env.JWT_SECRET) //verifies if token is generated by server, and is valid (expired or nah)
    req.user = decoded //decoded is the payload of the jwt
    //why req.user not req.body.user?
    //req.body is user input. treat as "untrusted"
    //req.user is system verified data. a reliable way for u to store verified and trusted var provided by ur server

    next()
  } catch (error) {// if token is invalid, it wld jump into this catch block. no requirement to check.
    res.status(400).json({ message: 'Invalid token.' })
  
}
}
export {authMiddleware}